// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.35;

/**
 * @title  LibHistory
 * @notice Encodes and queries a universe's path of inheritance through the fork tree as a bitmap,
 *         enabling O(1) ancestor checks via prefix matching.
 * @dev    Encoding is MSB-first / left-aligned. The genesis universe has `history == 0` and
 *         `forkDepth == 0`. Each binary fork appends one bit (the branch taken, 0 or 1) to the
 *         path; the bit for fork level `i` (0-based) lives at bit `255 - i`, so the oldest fork is
 *         the most-significant bit (i=0 -> bit 255, i=255 -> bit 0). A path of depth `d` therefore
 *         occupies the top `d` bits and the remaining `256 - d` low bits MUST be zero.
 *
 *         `forkDepth` is required to disambiguate paths: a branch-0 fork sets no bit, so a history
 *         alone cannot distinguish e.g. "0" (depth 1) from genesis (depth 0) — the depth carries
 *         that information. Ancestry is "A is an ancestor-or-equal of B if A's path is a prefix of
 *         B's path", which reduces to comparing the top `A.forkDepth` bits.
 *
 *         All functions are `pure` and operate only on their arguments. Malformed inputs (a history
 *         with bits set below its depth, or a depth above {MAX_FORK_DEPTH}) revert rather than
 *         returning a value: these are sanity checks that should never trigger for histories built
 *         by the system through {appendHistory}.
 */
library LibHistory {
    /// @notice Maximum fork depth. A path can hold at most 256 single-bit fork branches in a bytes32.
    uint256 public constant MAX_FORK_DEPTH = 256;

    /// @notice Thrown when a fork depth exceeds {MAX_FORK_DEPTH} (or would on append).
    error ForkDepthOverflow();
    /// @notice Thrown when a fork outcome index is not a valid binary branch (must be 0 or 1).
    error InvalidForkOutcomeIndex();
    /// @notice Thrown when a history has bits set below its declared depth (history/depth mismatch).
    error HistoryAndDepthMismatch();

    /**
     * @notice Appends a fork branch to a universe's path, producing the child universe's history.
     * @dev Reverts with {ForkDepthOverflow} if the parent is at or above {MAX_FORK_DEPTH},
     *      {HistoryAndDepthMismatch} if `history` has bits set below `forkDepth`, and
     *      {InvalidForkOutcomeIndex} if `forkOutcomeIndex > 1`. The new branch bit is placed at
     *      bit `256 - newForkDepth` (MSB-first); a branch of 0 leaves the bitmap unchanged and is
     *      distinguished only by the incremented depth.
     * @param history The parent universe's history bitmap.
     * @param forkDepth The parent universe's fork depth (number of branches in `history`).
     * @param forkOutcomeIndex The branch taken by the child: 0 or 1.
     * @return newHistory The child universe's history bitmap.
     * @return newForkDepth The child universe's fork depth (`forkDepth + 1`).
     */
    function appendHistory(bytes32 history, uint16 forkDepth, uint8 forkOutcomeIndex)
        internal
        pure
        returns (bytes32 newHistory, uint16 newForkDepth)
    {
        if ((forkDepth >= MAX_FORK_DEPTH)) {
            revert ForkDepthOverflow();
        }
        if (!isEmptyAfterDepth(history, forkDepth)) {
            revert HistoryAndDepthMismatch();
        }
        if (forkOutcomeIndex > 1) {
            revert InvalidForkOutcomeIndex();
        }
        newForkDepth = forkDepth + 1;
        newHistory = history | bytes32(uint256(forkOutcomeIndex) << (MAX_FORK_DEPTH - newForkDepth));
    }

    /**
     * @notice Returns whether one universe is an ancestor of (or equal to) another, i.e. whether the
     *         ancestor's path is a prefix of the descendant's path.
     * @dev O(1): compares the top `ancestorForkDepth` bits of both histories. The genesis universe
     *      (depth 0) is an ancestor of every universe. Reverts with {ForkDepthOverflow} if either
     *      depth exceeds {MAX_FORK_DEPTH}, or {HistoryAndDepthMismatch} if either history has bits
     *      set below its declared depth.
     * @param ancestorHistory The candidate ancestor's history bitmap.
     * @param ancestorForkDepth The candidate ancestor's fork depth.
     * @param descendantHistory The candidate descendant's history bitmap.
     * @param descendantForkDepth The candidate descendant's fork depth.
     * @return True if the ancestor's path is a prefix of the descendant's path (equal paths included).
     */
    function isAncestor(
        bytes32 ancestorHistory,
        uint16 ancestorForkDepth,
        bytes32 descendantHistory,
        uint16 descendantForkDepth
    ) internal pure returns (bool) {
        // Checks for malformed histories revert because that's a sanity check,
        // it should not happen in practice if the histories are generated by the system.
        if ((ancestorForkDepth > MAX_FORK_DEPTH) || (descendantForkDepth > MAX_FORK_DEPTH)) {
            revert ForkDepthOverflow();
        }
        if (!isEmptyAfterDepth(ancestorHistory, ancestorForkDepth)) {
            revert HistoryAndDepthMismatch();
        }
        if (!isEmptyAfterDepth(descendantHistory, descendantForkDepth)) {
            revert HistoryAndDepthMismatch();
        }
        // A deeper path can never be a prefix of a shallower one.
        if (ancestorForkDepth > descendantForkDepth) {
            return false;
        }
        // Compare the top `ancestorForkDepth` bits. At depth 0 the mask is 0 (shift by 256),
        // so genesis (history 0) matches every descendant.
        uint256 shift = MAX_FORK_DEPTH - ancestorForkDepth;
        uint256 mask = uint256(type(uint256).max) << shift;
        return ancestorHistory == (descendantHistory & bytes32(mask));
    }

    /**
     * @notice Returns whether a history has no bits set below its declared depth, i.e. only the top
     *         `depth` bits are used as the path.
     * @dev This is the well-formedness invariant for a (history, depth) pair. At `depth == 0` it
     *      requires `history == 0`; at `depth == MAX_FORK_DEPTH` the whole word is path so it is
     *      always true (the mask shifts to 0).
     *      The check that depth does not exceed {MAX_FORK_DEPTH} is left to the caller.
     * @param history The history bitmap to check.
     * @param depth The declared fork depth (number of leading path bits).
     * @return True if all bits below the top `depth` bits are zero.
     */
    function isEmptyAfterDepth(bytes32 history, uint16 depth) internal pure returns (bool) {
        uint256 mask = uint256(type(uint256).max) >> depth;
        return (history & bytes32(mask)) == 0;
    }
}
