name: foundry-ci

on:
  push:

jobs:
  foundry-ci:
    name: Forge fmt & test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Run Forge Build
        run: forge build

      - name: Forge format check
        run: forge fmt --check
        
      - name: Run Forge Test
        run: forge test
